version: 1.0.{build}
branches:
  only:
  - master
environment:
  NugetApiKey:
    secure: jiqlG8aCALzqxgzspfR8MdXMvcIEUF6JJp3a5fevRpGmLKgLHgv0o3lFMgg6xKKo
deploy_script:
- ps: Publish-Module -Name 'CoreService\Tridion-CoreService.psd1' -NuGetApiKey $env:NugetApiKey
  on: 
    branch: master
 build: off